version: '3'
services:
  backend:
    container_name: professor-redwood.backend.dev
    environment:
      DEBUG: '*'
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    volumes:
      - ./backend/src:/var/www/professor-redwood.backend/src

  db:
    container_name: professor-redwood.db.dev
    ports:
      - 27017:27017
    command: --smallfiles
    image: mongo
